### ISSUE TITLE
wined3d_allocator_chunk_gl_map failed

### ISSUE THREAD

**Issue by brandishcode** [emmanuelrosa/erosanix#20]
I was trying to run this old game (Ragnarok Online) using the `mkWindowsApp`. I am able to login to the game, and run it, but it will crash after around 20 seconds. I am getting this error related to wined3d and was wondering if you may have an idea why it might be happening?

```shell
03a0:err:d3d:wined3d_allocator_chunk_gl_map Failed to map chunk memory.
03a0:err:d3d:wined3d_bo_gl_map Failed to map chunk.
03a0:err:d3d:wined3d_context_gl_map_bo_address Failed to map bo.
```

Repository: https://github.com/brandishcode/ragnarok-nix

**Comment by emmanuelrosa** [comment]
No, unfortunately I don't recall ever seeing that error.

You can look at the Lutris installer and see if it gives you any hints: https://lutris.net/games/ragnarok-project-zero/

**Comment by emmanuelrosa** [comment]
Come to think of it, you can also try disabling Vulkan.

When Vulkan is enabled the Wine3d implementation is changed from Wine's built-in OpenGL to DVXK.

If the game uses DirectX 12, which doesn't seem to be the case, then another option is to use Wine's built-in Vulkan. For that you'd enable vulkan, but then also set the `renderOverride` to `wine-vulkan`.

**Comment by emmanuelrosa** [comment]
I played with it and got the same error.

It could be some kind of anti-cheat.

**Comment by brandishcode** [comment]
Hey thanks for checking. Oh, it might be, private servers these days do have anti-cheat system builtin. Might be impossible to bypass that one. Let me close this issue then.
