### ISSUE TITLE
mkWindowsApp feature to uninstall / clear broken install

### ISSUE THREAD

**Issue by crabdancing** [emmanuelrosa/erosanix#23]
In the event of an unsuccessful install, it's useful to be able to clear it and start it over. While this is certainly possible to do manually by running the derivation's bin terminal, making note of the relevant fs layer paths as they're printed, and deleting them, it's not ideal.

Some sort of special flag intercepted by `wine-launcher` would be a useful mechanism to quickly clear the installation, and would also double as a general-purpose uninstallation mechanism. Something along the lines of `--uninstall` or `--mkwindowsapp-uninstall`?

**Comment by emmanuelrosa** [comment]
I added an environment variable which causes the launcher to delete the app layer; The Windows layer is left alone since it may be used by another launcher.

Ex: `WA_CLEAN_APP=1 ./result/bin/whatever`
