### ISSUE TITLE
onlyoffice module seems to be broken

### ISSUE THREAD

**Issue by nikp123** [emmanuelrosa/erosanix#6]
![image](https://user-images.githubusercontent.com/4696350/232610760-6c36d9f6-3fd2-4f6e-a136-ae429ded5e52.png)
![image](https://user-images.githubusercontent.com/4696350/232610810-3bf92d8e-d4f3-4da1-bbfe-bd9f75946b17.png)

**Comment by nikp123** [comment]
also i think i can patch onlyoffice instead
https://github.com/ONLYOFFICE/core/blob/02c78a1e6fb91260b371ccaa051e5d66a5d637c8/DesktopEditor/fontengine/ApplicationFonts.cpp#L1780

**Comment by nikp123** [comment]
yep
https://search.nixos.org/options?channel=22.11&show=fonts.fontDir.enable&from=0&size=50&sort=relevance&type=packages&query=font
though, this is a massive hack

**Comment by nikp123** [comment]
didnt work because onlyoffice was built from binary, but they've thankfully added a CUSTOM_PATH to play around with https://github.com/ONLYOFFICE/core/pull/815/commits/68582b65d1ce158b22d0665f096480982df816d6

**Comment by nikp123** [comment]
bummer, it doesn't work with symlinks. though, you could use something like this in order to get fonts to work

**Comment by nikp123** [comment]
worked a *bad* solution, but it's a solution:
```
  nixpkgs.overlays = [
    ( self: super: {
      onlyoffice-bin = super.onlyoffice-bin.overrideAttrs (old: {
        preFixup = (old.preFixup or "") + ''
          gappsWrapperArgs+=(
            --set CUSTOM_FONTS_PATH "${pkgs.microsoft-fonts}/share/fonts/TTF"  # or whatever font you desire to use
          )
        '';
      });
    })
  ];
  ```

**Comment by emmanuelrosa** [comment]
Yes, ONLYOFFICE has a known issue (which I've reported) when /usr/share/fonts contains symlinks. The ONLYOFFICE module uses the code from `fonts.fontDir.enable` but I copy the fonts instead of creating symlinks to them.

I'm unable to reproduce your error. Can you show me the build log?

**Comment by nikp123** [comment]
> Yes, ONLYOFFICE has a known issue (which I've reported) when /usr/share/fonts contains symlinks. The ONLYOFFICE module uses the code from `fonts.fontDir.enable` but I copy the fonts instead of creating symlinks to them.
> 
> I'm unable to reproduce your error. Can you show me the build log?

The log is quite boring, as it's just a simple "folder not found" error.
[log.txt](https://github.com/emmanuelrosa/erosanix/files/11345557/log.txt)

**Comment by nikp123** [comment]
I imported your module as a flake, that's the only thing I did.
And I've imported it via: ``erosanix.nixosModules.onlyoffice``

**Comment by emmanuelrosa** [comment]
I pushed an update that I think will fix it.

The error message is correct in that the given path is not a directory; It's a symlink. The update copies the icons instead of using a symlink. There must be a difference between how that's handled on NixOS 22.11 and NixOS master.

**Comment by nikp123** [comment]
![image](https://user-images.githubusercontent.com/4696350/234948271-7b695803-df4c-4f97-8472-712e2bbf2333.png)

Uh, yeah, more bugs to crush unfortunately.

**Comment by emmanuelrosa** [comment]
OK, I see that the package on NixOS 21.11 doesn't have icons. I pushed an update that should work around that.

**Comment by nikp123** [comment]
Works perfectly now, thank you.
